// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNe_ewW7NRYUs2_A9T5Aa2KmUTbPivz-U',
    appId: '1:996056969194:web:3a8fa4d68111b630470c93',
    messagingSenderId: '996056969194',
    projectId: 'aset-fde87',
    authDomain: 'aset-fde87.firebaseapp.com',
    databaseURL: 'https://aset-fde87-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aset-fde87.appspot.com',
    measurementId: 'G-B9WZ1YF6EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_O6oIHlW3sGcZzSHX_bUO8SGGFB8SNnc',
    appId: '1:996056969194:android:98aa7612fd964dc3470c93',
    messagingSenderId: '996056969194',
    projectId: 'aset-fde87',
    databaseURL: 'https://aset-fde87-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aset-fde87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm7LlbXhqIzK3uws3kdvipR9yNkpVOKSg',
    appId: '1:996056969194:ios:d9d73dd80fcec3f9470c93',
    messagingSenderId: '996056969194',
    projectId: 'aset-fde87',
    databaseURL: 'https://aset-fde87-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aset-fde87.appspot.com',
    iosBundleId: 'com.example.heloworldapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm7LlbXhqIzK3uws3kdvipR9yNkpVOKSg',
    appId: '1:996056969194:ios:ac0ad1668488c5a3470c93',
    messagingSenderId: '996056969194',
    projectId: 'aset-fde87',
    databaseURL: 'https://aset-fde87-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aset-fde87.appspot.com',
    iosBundleId: 'com.example.heloworldapp.RunnerTests',
  );
}